### ISSUE TITLE
Is there a FOSS license for this code?

### ISSUE THREAD

**Issue by grokify** [go-leap/dev#1]
Is there a FOSS license for code here and at the following locations?

1. https://github.com/go-leap
2. https://github.com/metaleap/go-util

**Comment by metaleap** [comment]
Yes, hereby declared that the latter is licensed under the [WTFPL](https://en.wikipedia.org/wiki/WTFPL).

The former link, not my stuff.

**Comment by grokify** [comment]
> The former link, not my stuff.

Updated to https://github.com/go-leap from https://github.com/go-util .

**Comment by metaleap** [comment]
Cool, same license as above hereby decreed  =)

**Comment by grokify** [comment]
Thanks!

Looking into this to try out https://github.com/metaleap/go-xsd.
